name: lena
favicon: null
layout_spectrum: 0.05068853544071317
typography_spectrum: 0.047999039525166154
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9151598259340972
  lightness: 0.4739237923640758
  saturation: 0.2452032808214426
  rhythmicContrast: 0.5526423880364746
purpose: []
